
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild 縺ｮ繝舌・繧ｸ繝ｧ繝ｳ 17.11.2+c078802d4 (.NET Framework)
      2024/09/07 22:54:04 縺ｫ繝薙Ν繝峨ｒ髢句ｧ九＠縺ｾ縺励◆縲・
      
      繝弱・繝・1 荳翫・繝励Ο繧ｸ繧ｧ繧ｯ繝・"C:\\Users\\main\\IdeaProjects\\java-uef\\cbuild\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (譌｢螳壹・繧ｿ繝ｼ繧ｲ繝・ヨ)縲・
      PrepareForBuild:
        繝・ぅ繝ｬ繧ｯ繝医Μ "Debug\\" 繧剃ｽ懈・縺励※縺・∪縺吶\xc2\x80・
        讒矩\xc2\x80蛹門・蜉帙′譛牙柑縺ｫ縺ｪ縺｣縺ｦ縺・∪縺吶\xc2\x80ゅさ繝ｳ繝代う繝ｩ險ｺ譁ｭ縺ｮ譖ｸ蠑剰ｨｭ螳壹↓縺ｯ繧ｨ繝ｩ繝ｼ髫主ｱ､縺悟渚譏縺輔ｌ縺ｾ縺吶\xc2\x80りｩｳ邏ｰ縺ｫ縺､縺・※縺ｯ縲”ttps://aka.ms/cpp/structured-output 繧貞盾辣ｧ縺励※縺上□縺輔＞縲・
        繝・ぅ繝ｬ繧ｯ繝医Μ "Debug\\CompilerIdCXX.tlog\\" 繧剃ｽ懈・縺励※縺・∪縺吶\xc2\x80・
      InitializeBuildStatus:
        "AlwaysCreate" 縺梧欠螳壹＆繧後◆縺溘ａ "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" 繧剃ｽ懈・縺励※縺・∪縺吶\xc2\x80・
        "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" 縺ｮ繧ｿ繝・メ 繧ｿ繧ｹ繧ｯ繧貞ｮ溯｡後＠縺ｦ縺・∪縺吶\xc2\x80・
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\main\\IdeaProjects\\java-uef\\cbuild\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        繝輔ぃ繧､繝ｫ "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" 繧貞炎髯､縺励※縺・∪縺吶\xc2\x80・
        "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate" 縺ｮ繧ｿ繝・メ 繧ｿ繧ｹ繧ｯ繧貞ｮ溯｡後＠縺ｦ縺・∪縺吶\xc2\x80・
      繝励Ο繧ｸ繧ｧ繧ｯ繝・"C:\\Users\\main\\IdeaProjects\\java-uef\\cbuild\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (譌｢螳壹・繧ｿ繝ｼ繧ｲ繝・ヨ) 縺ｮ繝薙Ν繝峨′螳御ｺ・＠縺ｾ縺励◆縲・
      
      繝薙Ν繝峨↓謌仙粥縺励∪縺励◆縲・
          0 蛟九・隴ｦ蜻・
          0 繧ｨ繝ｩ繝ｼ
      
      邨碁℃譎る俣 00:00:00.48
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/main/IdeaProjects/java-uef/cbuild/CMakeFiles/3.30.2/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/main/IdeaProjects/java-uef/cbuild/CMakeFiles/CMakeScratch/TryCompile-y2x6ro"
      binary: "C:/Users/main/IdeaProjects/java-uef/cbuild/CMakeFiles/CMakeScratch/TryCompile-y2x6ro"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/main/IdeaProjects/java-uef/cbuild/CMakeFiles/CMakeScratch/TryCompile-y2x6ro'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_52d09.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild 縺ｮ繝舌・繧ｸ繝ｧ繝ｳ 17.11.2+c078802d4 (.NET Framework)
        2024/09/07 22:54:04 縺ｫ繝薙Ν繝峨ｒ髢句ｧ九＠縺ｾ縺励◆縲・
        
        繝弱・繝・1 荳翫・繝励Ο繧ｸ繧ｧ繧ｯ繝・"C:\\Users\\main\\IdeaProjects\\java-uef\\cbuild\\CMakeFiles\\CMakeScratch\\TryCompile-y2x6ro\\cmTC_52d09.vcxproj" (譌｢螳壹・繧ｿ繝ｼ繧ｲ繝・ヨ)縲・
        PrepareForBuild:
          繝・ぅ繝ｬ繧ｯ繝医Μ "cmTC_52d09.dir\\Debug\\" 繧剃ｽ懈・縺励※縺・∪縺吶\xc2\x80・
          讒矩\xc2\x80蛹門・蜉帙′譛牙柑縺ｫ縺ｪ縺｣縺ｦ縺・∪縺吶\xc2\x80ゅさ繝ｳ繝代う繝ｩ險ｺ譁ｭ縺ｮ譖ｸ蠑剰ｨｭ螳壹↓縺ｯ繧ｨ繝ｩ繝ｼ髫主ｱ､縺悟渚譏縺輔ｌ縺ｾ縺吶\xc2\x80りｩｳ邏ｰ縺ｫ縺､縺・※縺ｯ縲”ttps://aka.ms/cpp/structured-output 繧貞盾辣ｧ縺励※縺上□縺輔＞縲・
          繝・ぅ繝ｬ繧ｯ繝医Μ "C:\\Users\\main\\IdeaProjects\\java-uef\\cbuild\\CMakeFiles\\CMakeScratch\\TryCompile-y2x6ro\\Debug\\" 繧剃ｽ懈・縺励※縺・∪縺吶\xc2\x80・
          繝・ぅ繝ｬ繧ｯ繝医Μ "cmTC_52d09.dir\\Debug\\cmTC_52d09.tlog\\" 繧剃ｽ懈・縺励※縺・∪縺吶\xc2\x80・
        InitializeBuildStatus:
          "AlwaysCreate" 縺梧欠螳壹＆繧後◆縺溘ａ "cmTC_52d09.dir\\Debug\\cmTC_52d09.tlog\\unsuccessfulbuild" 繧剃ｽ懈・縺励※縺・∪縺吶\xc2\x80・
          "cmTC_52d09.dir\\Debug\\cmTC_52d09.tlog\\unsuccessfulbuild" 縺ｮ繧ｿ繝・メ 繧ｿ繧ｹ繧ｯ繧貞ｮ溯｡後＠縺ｦ縺・∪縺吶\xc2\x80・
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_52d09.dir\\Debug\\\\" /Fd"cmTC_52d09.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.30\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft(R) C/C++ Optimizing Compiler Version 19.41.34120 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_52d09.dir\\Debug\\\\" /Fd"cmTC_52d09.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.30\\Modules\\CMakeCXXCompilerABI.cpp"
          CMakeCXXCompilerABI.cpp
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\main\\IdeaProjects\\java-uef\\cbuild\\CMakeFiles\\CMakeScratch\\TryCompile-y2x6ro\\Debug\\cmTC_52d09.exe" /INCREMENTAL /ILK:"cmTC_52d09.dir\\Debug\\cmTC_52d09.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/main/IdeaProjects/java-uef/cbuild/CMakeFiles/CMakeScratch/TryCompile-y2x6ro/Debug/cmTC_52d09.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/main/IdeaProjects/java-uef/cbuild/CMakeFiles/CMakeScratch/TryCompile-y2x6ro/Debug/cmTC_52d09.lib" /MACHINE:X64  /machine:x64 cmTC_52d09.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_52d09.vcxproj -> C:\\Users\\main\\IdeaProjects\\java-uef\\cbuild\\CMakeFiles\\CMakeScratch\\TryCompile-y2x6ro\\Debug\\cmTC_52d09.exe
        FinalizeBuildStatus:
          繝輔ぃ繧､繝ｫ "cmTC_52d09.dir\\Debug\\cmTC_52d09.tlog\\unsuccessfulbuild" 繧貞炎髯､縺励※縺・∪縺吶\xc2\x80・
          "cmTC_52d09.dir\\Debug\\cmTC_52d09.tlog\\cmTC_52d09.lastbuildstate" 縺ｮ繧ｿ繝・メ 繧ｿ繧ｹ繧ｯ繧貞ｮ溯｡後＠縺ｦ縺・∪縺吶\xc2\x80・
        繝励Ο繧ｸ繧ｧ繧ｯ繝・"C:\\Users\\main\\IdeaProjects\\java-uef\\cbuild\\CMakeFiles\\CMakeScratch\\TryCompile-y2x6ro\\cmTC_52d09.vcxproj" (譌｢螳壹・繧ｿ繝ｼ繧ｲ繝・ヨ) 縺ｮ繝薙Ν繝峨′螳御ｺ・＠縺ｾ縺励◆縲・
        
        繝薙Ν繝峨↓謌仙粥縺励∪縺励◆縲・
            0 蛟九・隴ｦ蜻・
            0 繧ｨ繝ｩ繝ｼ
        
        邨碁℃譎る俣 00:00:00.44
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:218 (message)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Parsed CXX implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'CXX': C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/HostX64/x64/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/Internal/CMakeDetermineLinkerId.cmake:40 (message)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:255 (cmake_determine_linker_id)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Running the CXX compiler's linker: "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/HostX64/x64/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.41.34120.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CheckSourceCompiles.cmake:77 (cmake_check_source_compiles)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/FindJNI.cmake:485 (check_source_compiles)"
      - "CMakeLists.txt:8 (find_package)"
    directories:
      source: "C:/Users/main/IdeaProjects/java-uef/cbuild/CMakeFiles/CMakeScratch/TryCompile-83o31f"
      binary: "C:/Users/main/IdeaProjects/java-uef/cbuild/CMakeFiles/CMakeScratch/TryCompile-83o31f"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "JNI_INCLUDE_PATH2_OPTIONAL"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/main/IdeaProjects/java-uef/cbuild/CMakeFiles/CMakeScratch/TryCompile-83o31f'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_470a3.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild 縺ｮ繝舌・繧ｸ繝ｧ繝ｳ 17.11.2+c078802d4 (.NET Framework)
        2024/09/07 22:54:05 縺ｫ繝薙Ν繝峨ｒ髢句ｧ九＠縺ｾ縺励◆縲・
        
        繝弱・繝・1 荳翫・繝励Ο繧ｸ繧ｧ繧ｯ繝・"C:\\Users\\main\\IdeaProjects\\java-uef\\cbuild\\CMakeFiles\\CMakeScratch\\TryCompile-83o31f\\cmTC_470a3.vcxproj" (譌｢螳壹・繧ｿ繝ｼ繧ｲ繝・ヨ)縲・
        PrepareForBuild:
          繝・ぅ繝ｬ繧ｯ繝医Μ "cmTC_470a3.dir\\Debug\\" 繧剃ｽ懈・縺励※縺・∪縺吶\xc2\x80・
          讒矩\xc2\x80蛹門・蜉帙′譛牙柑縺ｫ縺ｪ縺｣縺ｦ縺・∪縺吶\xc2\x80ゅさ繝ｳ繝代う繝ｩ險ｺ譁ｭ縺ｮ譖ｸ蠑剰ｨｭ螳壹↓縺ｯ繧ｨ繝ｩ繝ｼ髫主ｱ､縺悟渚譏縺輔ｌ縺ｾ縺吶\xc2\x80りｩｳ邏ｰ縺ｫ縺､縺・※縺ｯ縲”ttps://aka.ms/cpp/structured-output 繧貞盾辣ｧ縺励※縺上□縺輔＞縲・
          繝・ぅ繝ｬ繧ｯ繝医Μ "C:\\Users\\main\\IdeaProjects\\java-uef\\cbuild\\CMakeFiles\\CMakeScratch\\TryCompile-83o31f\\Debug\\" 繧剃ｽ懈・縺励※縺・∪縺吶\xc2\x80・
          繝・ぅ繝ｬ繧ｯ繝医Μ "cmTC_470a3.dir\\Debug\\cmTC_470a3.tlog\\" 繧剃ｽ懈・縺励※縺・∪縺吶\xc2\x80・
        InitializeBuildStatus:
          "AlwaysCreate" 縺梧欠螳壹＆繧後◆縺溘ａ "cmTC_470a3.dir\\Debug\\cmTC_470a3.tlog\\unsuccessfulbuild" 繧剃ｽ懈・縺励※縺・∪縺吶\xc2\x80・
          "cmTC_470a3.dir\\Debug\\cmTC_470a3.tlog\\unsuccessfulbuild" 縺ｮ繧ｿ繝・メ 繧ｿ繧ｹ繧ｯ繧貞ｮ溯｡後＠縺ｦ縺・∪縺吶\xc2\x80・
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX64\\x64\\CL.exe /c /I"C:\\Program Files\\Java\\jdk-21\\include" /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D JNI_INCLUDE_PATH2_OPTIONAL /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++17 /Fo"cmTC_470a3.dir\\Debug\\\\" /Fd"cmTC_470a3.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Users\\main\\IdeaProjects\\java-uef\\cbuild\\CMakeFiles\\CMakeScratch\\TryCompile-83o31f\\src.cxx"
          Microsoft(R) C/C++ Optimizing Compiler Version 19.41.34120 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /I"C:\\Program Files\\Java\\jdk-21\\include" /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D JNI_INCLUDE_PATH2_OPTIONAL /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++17 /Fo"cmTC_470a3.dir\\Debug\\\\" /Fd"cmTC_470a3.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Users\\main\\IdeaProjects\\java-uef\\cbuild\\CMakeFiles\\CMakeScratch\\TryCompile-83o31f\\src.cxx"
          src.cxx
        C:\\Program Files\\Java\\jdk-21\\include\\jni.h(45,10): error C1083: include 繝輔ぃ繧､繝ｫ繧帝幕縺代∪縺帙ｓ縲・jni_md.h':No such file or directory [C:\\Users\\main\\IdeaProjects\\java-uef\\cbuild\\CMakeFiles\\CMakeScratch\\TryCompile-83o31f\\cmTC_470a3.vcxproj]
          (繧ｽ繝ｼ繧ｹ 繝輔ぃ繧､繝ｫ 'src.cxx' 繧偵さ繝ｳ繝代う繝ｫ縺励※縺・∪縺・
          
        繝励Ο繧ｸ繧ｧ繧ｯ繝・"C:\\Users\\main\\IdeaProjects\\java-uef\\cbuild\\CMakeFiles\\CMakeScratch\\TryCompile-83o31f\\cmTC_470a3.vcxproj" (譌｢螳壹・繧ｿ繝ｼ繧ｲ繝・ヨ) 縺ｮ繝薙Ν繝峨′邨ゆｺ・＠縺ｾ縺励◆ -- 螟ｱ謨励\xc2\x80・
        
        繝薙Ν繝峨↓螟ｱ謨励＠縺ｾ縺励◆縲・
        
        "C:\\Users\\main\\IdeaProjects\\java-uef\\cbuild\\CMakeFiles\\CMakeScratch\\TryCompile-83o31f\\cmTC_470a3.vcxproj" (譌｢螳壹・繧ｿ繝ｼ繧ｲ繝・ヨ) (1) ->
        (ClCompile 繧ｿ繝ｼ繧ｲ繝・ヨ) -> 
          C:\\Program Files\\Java\\jdk-21\\include\\jni.h(45,10): error C1083: include 繝輔ぃ繧､繝ｫ繧帝幕縺代∪縺帙ｓ縲・jni_md.h':No such file or directory [C:\\Users\\main\\IdeaProjects\\java-uef\\cbuild\\CMakeFiles\\CMakeScratch\\TryCompile-83o31f\\cmTC_470a3.vcxproj]
        
            0 蛟九・隴ｦ蜻・
            1 繧ｨ繝ｩ繝ｼ
        
        邨碁℃譎る俣 00:00:00.31
        
      exitCode: 1
...
